### ISSUE TITLE
Wrong (future) tasks dismissed

### ISSUE THREAD

**Issue by srslykev** [RogerSelwyn/MS365-ToDo#25]
Hey there, 

unfortunately, when I dismiss a due recurring task, the upcoming task appears and is marked as done, while the due task stays due. 

Am I the only one experiencing this? 

Thanks a lot for the great work!

**Comment by RogerSelwyn** [comment]
I don’t think I was aware there was such a thing as a recurring task. I will need to take a look. 

Are you dismissing via the HA core ToDo panel, because it is possible it doesn’t support recurring tasks.

**Comment by srslykev** [comment]
Thanks for the quick reply! It happens both in the panel as well as the todo lovelace card.

**Comment by RogerSelwyn** [comment]
No idea about the todo Lovelace card since it is not created by me. Again, it probably doesn’t support recurring tasks. However I will take a look next week some time.

**Comment by RogerSelwyn** [comment]
Can you try this version and see if it fixes the issue. I suspect there will be issues, because I don't believe HA core handles recurring tasks. Looking at the MS Graph Explorer, all occurrences have the same task id, so no idea how you tell which one you are updating. If recurring tasks is newish, it is possible the api doesn't support it, as has been the case for other items.

https://github.com/RogerSelwyn/MS365-ToDo/releases/tag/v0.1.3b1

**Comment by srslykev** [comment]
I think, this does ist. I've tried a few times and now, the correct task is dismissed. I've just noticed, that in the non beta version, a new recurring task had been created on top of the existing one. But the beta fixes this, thanks a lot!
I've been using that feature for years, so it's not really new..

**Comment by RogerSelwyn** [comment]
I'll try to figure out how updating a recurring task works in the api, to make it more reliable. For sure the HA core does not support it, but I may be able to make it work.

For example, if you try to change the completed task that the todo panel shows, I don't think that will work.

**Comment by srslykev** [comment]
Cool, thanks!
I don't think editing recurring tasks is that important, since they are mostly setup and forgotten about.

**Comment by RogerSelwyn** [comment]
I've checked again, they all do have unique iDs, so why the wrong one was being completed I have no idea. That said, I am hopeful the change I have made will fix it.
