### ISSUE TITLE
My Day List not showing up

### ISSUE THREAD

**Issue by anseld1986** [RogerSelwyn/MS365-ToDo#27]
No problems installing the integration but the (semi-auto-populated) My Day list within To Do doesn't show up in the lists passed to Home Assistant.

**Comment by RogerSelwyn** [comment]
Unfortunately `My Day` isn't a real list, it is something handled within the MS To Do app. You can check this by entering this url in MS Graph Explorer - https://graph.microsoft.com/v1.0/me/todo/lists

https://www.reddit.com/r/MicrosoftFlow/comments/yxjhuf/update_a_microsoft_todo_task_to_set_the_my_day/
