### ISSUE TITLE
setup - authentication problem

### ISSUE THREAD

**Issue by mmlody** [RogerSelwyn/MS365-ToDo#36]
hello

I gave problem with authentication Mail modulu
Everything prepared step by step with documentation, i try authenticate with alternate method (HA available from public internet)
Everytime when I try to authenticate (click on "Link MS365 account" in home assistant I always get error from Microsoft aboy bad return url

"AADSTS50011: The redirect URI 'https://ha._MASKED_PUBLIC_DOMAIN/api/ms365' specified in the request does not match the redirect URIs configured for the application"

In documentation return URL is https://PUBLIC_URL_OF_HA/api/ms365_todo and this URL is entered to app registration in AAD

Why return url returned by microsft was trimmed down only to /api/ms365 ?
When I try to open URL builed with documentation (http://PUBLIC_URL_OF_MY_HA/api/ms365_todo I always get only "404. Not Found"

![image](https://github.com/user-attachments/assets/0c08fa6d-c629-4380-bd7b-1d4efddd0e8d)

Another intergration to 365 platform (old O365-HomeAssistant https://github.com/RogerSelwyn/O365-HomeAssistant) I configured without problems but sending mails from this old integration not working 

Is "new" Mail integration ready to configuration and use ?

**Comment by RogerSelwyn** [comment]
I'll check it next week (25th) when I get a chance.

**Comment by mmlody** [comment]
> I'll check it next week (25th) when I get a chance.

Sure 

One small thing:
return URL sie same in module _ToDo and _Mail ?

From documentation of _Mail module

![image](https://github.com/user-attachments/assets/5d074deb-a09c-455e-80a7-311a82b82577)

From documentation od _ToDo module

![image](https://github.com/user-attachments/assets/6ba1509d-8607-4026-8250-ee93c7fa519e)

**Comment by RogerSelwyn** [comment]
I think if you adjust the url on your Entra Id app, to just ma365, it should work.

**Comment by RogerSelwyn** [comment]
Yep, pretty sure that should work, looking at the code. So it is the same url for all integrations (apart from o365).

**Comment by mmlody** [comment]
Yes

After URL change authentication was sucessful.

śr., 20 lis 2024, 17:53 użytkownik RogerSelwyn ***@***.***>
napisał:
