### ISSUE TITLE
Tasks appear read-only

### ISSUE THREAD

**Issue by jarodwsams** [RogerSelwyn/MS365-ToDo#40]
I've just added this integration to replace the older O365 version (calendar, too). So far, excellent. Except that my to-do list items, for the lists I've chosen to synchronize, all appear to be read-only.

I followed the setup instructions, except for the part about signing up for a "pay as you go" Azure account to get the new Entra ID thing. I already had an Application in place for the older O365 integration, and I was able to auth both the calendar integration and this using that old client id/secret.

Thinking there was an update I needed to make to the app permissions, I reviewed all of that. Application permissions are correct, according to the documentation. I also checked the token file in the hidden directory and it's registered the "Tasks.ReadWrite" permission.

I did restart Home Assistant after installing the integration, though it was not a host reboot. I'm doing a host reboot as I type this, just for good measure.

Not sure what else to look at. The only thing I can think _might_ be the issue is the fact that I did not create a new application with a new Entra ID, but if the permissions from my existing app are correct I assumed I'd be okay.

**Comment by jarodwsams** [comment]
Just circling back... doing a host reboot did not resolve the issue

**Comment by RogerSelwyn** [comment]
Did you enable updates on initial configuration? If not, click on the three dots and select reconfigure, and enable updates.

**Comment by RogerSelwyn** [comment]
No further comment, so assumed fixed.

**Comment by jarodwsams** [comment]
So sorry, I never got the email message that there was a comment on this issue, and I just now remembered to check it. Thank you for the "update services" bit, though. That fixed it. I could have sworn I enabled that the first time.
