### ISSUE TITLE
Unable to set up

### ISSUE THREAD

**Issue by JonahMMay** [RogerSelwyn/MS365-ToDo#42]
Debug log snippet:

```
2024-11-25 11:40:52.952 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Jonah_MayFamily_ToDo for ms365_todo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ms365_todo/__init__.py", line 50, in async_setup_entry
    coordinator, sensors, platforms = await async_do_setup(hass, entry, account)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ms365_todo/integration/setup_integration.py", line 19, in async_do_setup
    await sensor_coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 308, in async_config_entry_first_refresh
    if await self.__wrap_async_setup():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 321, in __wrap_async_setup
    await self._async_setup()
  File "/config/custom_components/ms365_todo/integration/coordinator_integration.py", line 64, in _async_setup
    todo_keys = await self._async_todo_sensors()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ms365_todo/integration/coordinator_integration.py", line 69, in _async_todo_sensors
    await async_scan_for_todo_lists(self.hass, self._account, self._entry)
  File "/config/custom_components/ms365_todo/integration/todo_integration.py", line 484, in async_scan_for_todo_lists
    todolists = await hass.async_add_executor_job(todos.list_folders)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError
```

Calendar integration works fine and all permissions are added. Rebooting makes the integration disappear from the list. Attempting to re-add it gives `This account name has already been used. Use re-configure.

**Comment by RogerSelwyn** [comment]
Please also run this query in [MS Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) and let me know if it gives the expected result:

`https://graph.microsoft.com/v1.0/me/todo/lists`

**Comment by JonahMMay** [comment]
That snippet above is from the diagnostics and yes it is disappearing from Devices & Services. Here are the results of the query: 
```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users/$entity",
    "@microsoft.graph.tips": "This request only returns a subset of the resource's properties. Your app will need to use $select to return non-default properties. To find out what other properties are available for this resource see https://learn.microsoft.com/graph/api/resources/user",
    "businessPhones": [],
    "displayName": "Jonah May",
    "givenName": null,
    "jobTitle": null,
    "mail": "jonah@mayfamily.me",
    "mobilePhone": null,
    "officeLocation": null,
    "preferredLanguage": null,
    "surname": null,
    "userPrincipalName": "jonah@mayfamily.me",
    "id": "73acc7db-673c-4bbc-aa1e-3bc9c19d19d4"
}
```

**Comment by JonahMMay** [comment]
Looks like there might be some sort of outage. The app on my phone and desktop both say last synced 1 hour ago, and attempting to access to-do.office.com gives me a 503 error.

**Comment by RogerSelwyn** [comment]
> That snippet above is from the diagnostics and yes it is disappearing from Devices & Services. Here are the results of the query:
> 
> ```
> {
>     "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users/$entity",
>     "@microsoft.graph.tips": "This request only returns a subset of the resource's properties. Your app will need to use $select to return non-default properties. To find out what other properties are available for this resource see https://learn.microsoft.com/graph/api/resources/user",
>     "businessPhones": [],
>     "displayName": "Jonah May",
>     "givenName": null,
>     "jobTitle": null,
>     "mail": "redacted",
>     "mobilePhone": null,
>     "officeLocation": null,
>     "preferredLanguage": null,
>     "surname": null,
>     "userPrincipalName": "redacted",
>     "id": "73acc7db-673c-4bbc-aa1e-3bc9c19d19d4"
> }
> ```

I've removed your email from this. That is a response to /me, not /me/todo/lists.

That previous post was from the system logs, not a diagnostic which is downloaded by clicking on three dots of the integration and selecting 'Download diagnostics'.  Please post the full error from the log, please do not cut it short.
