### ISSUE TITLE
Missing Lists

### ISSUE THREAD

**Issue by seffyroff** [RogerSelwyn/MS365-ToDo#50]
Hey there, thanks for making this!

I am missing some lists after setting it up.  it seems to have imported exactly 50 lists - is that a hard limit perhaps? I have more than that.

Some of the lists are of the type 'shared lists' which maybe aren't supported?

Thanks for your time and effort.

**Comment by RogerSelwyn** [comment]
You can check what lists it will display using this query in MS Graph Explorer - https://graph.microsoft.com/v1.0/me/todo/lists

I don't believe MS support shared lists in the api.

**Comment by RogerSelwyn** [comment]
No further information provided
