### ISSUE TITLE
Can´t add/edit items on list

### ISSUE THREAD

**Issue by philcordes** [RogerSelwyn/MS365-ToDo#51]
Hello Roger,
thanks a lot for your work!
Reading the lists works fine but I can´t add items or mark them as done.
Any hint (I have set the Tasks.ReadWrite in the API-permissions)?

**Comment by RogerSelwyn** [comment]
Did you enable update in the configuration?

**Comment by philcordes** [comment]
Ah, no. 
Sorry to ask: which is the configuration file that I have to change?

**Comment by RogerSelwyn** [comment]
It’s not in a configuration file, it’s in the configuration of the integration. Click on the there dots and select reconfigure.

**Comment by philcordes** [comment]
Aah, I had overlooked that. Works now - thanks a lot! :)
