### ISSUE TITLE
token_file_error

### ISSUE THREAD

**Issue by dphotograph** [RogerSelwyn/MS365-ToDo#8]
Hi there,

i have an problem to Authenticaate my App with the HA Interation MS365-ToDo

I cant Authenticate the App.

After i created the WEB App in Azure and created the Client secret. 
I tryed to Add the Integration to Home Assistant fill out the needed Informations like 
Name for the Entities, Client ID and Client Secret. 
here i can send the configration.

in the next Popup i klick the Link "Link MS365 account" Allow the needed options and left with the needed URL in the Browser if i Copy the URL and paste it in the Popup in Homeassistant i just  see the "token_file_error" prompt

at this point i am shure i did something wrong but hopefully someone here sees this here and can help me with my problem.

Thank You :-)

**Comment by RogerSelwyn** [comment]
What errors are shown in the system log?

**Comment by dphotograph** [comment]
Hi! 
I absolutely have to apologize!
i am just really dumb! 
when copying the client secrets of the web app on Azure
There was an underscore at the beginning of the client secret that didn't find its way into my Notepad when I first copied it from Azure...

Your Integration is now running smothly 

Thanks for your fast try to help me

**Comment by jpbaril** [comment]
Same issue here.
Probably did something wrong, but I don't know what. I followed instructions twice but cannot figure what is wrong.
I created an Azure account, created the app (with "Accounts in any organizational directory (Any Azure AD directory - Multitenant) and personal Microsoft accounts (e.g. Skype, Xbox)"), added redirect URLs, added permissions. created secret.
Still not working.
Where can I see logs to understand the error?
Thank you

**Comment by RogerSelwyn** [comment]
Look in the Home Assistant system logs

**Comment by jpbaril** [comment]
Damn, I hate to be an idiot! 
![Capture d’écran du 2024-07-30 15-57-17](https://github.com/user-attachments/assets/0fd5c5e5-0ef4-41e7-96fb-cbdfee11107e)

**Comment by RogerSelwyn** [comment]
I guessed it was likely that. Problem is MS365 is not very good at telling you what the problem is before it just doesn’t work.
